name: ezeml
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - alembic=1.17.2
  - attrs=25.4.0
  - backports.zstd=1.2.0
  - blinker=1.9.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cachetools=6.2.2
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.1
  - colorama=0.4.6
  - cryptography=46.0.3
  - daiquiri=3.0.0
  - dnspython=2.8.0
  - dominate=2.9.1
  - email-validator=2.3.0
  - email_validator=2.3.0
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.1
  - flask=3.1.2
  - flask-bootstrap=3.3.7.1
  - flask-login=0.6.3
  - flask-migrate=4.1.0
  - flask-sqlalchemy=3.1.1
  - flask-wtf=1.2.2
  - frozenlist=1.7.0
  - google-auth=2.43.0
  - google-auth-oauthlib=1.2.2
  - greenlet=3.3.0
  - gspread=5.12.4
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - iniconfig=2.3.0
  - itsdangerous=2.2.0
  - jansson=2.14.1
  - jinja2=3.1.6
  - ld_impl_linux-64=2.45
  - libblas=3.11.0
  - libcblas=3.11.0
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - mako=1.3.10
  - markupsafe=3.0.3
  - multidict=6.6.3
  - ncurses=6.5
  - numpy=2.3.5
  - oauthlib=3.3.1
  - openpyxl=3.1.5
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.47
  - pendulum=3.1.0
  - pip=25.3
  - pluggy=1.6.0
  - propcache=0.3.1
  - psutil=7.1.3
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pympler=1.1
  - pyopenssl=25.3.0
  - pysocks=1.7.1
  - pytest=9.0.2
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyu2f=0.1.5
  - readline=8.2
  - requests=2.32.5
  - requests-file=3.0.1
  - requests-oauthlib=2.0.0
  - rfc3986=2.0.0
  - rsa=4.9.1
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.1
  - sqlalchemy=2.0.44
  - time-machine=3.1.0
  - tk=8.6.13
  - tomli=2.3.0
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.1
  - uwsgi=2.0.31
  - visitor=0.1.3
  - werkzeug=3.1.4
  - wheel=0.45.1
  - wtforms=3.2.1
  - yaml=0.2.5
  - yarl=1.22.0
  - zipp=3.23.0
  - zstd=1.5.7
  - pip:
      - emlvp==1.2.6
      - lxml==5.4.0
      - metapype==0.1.1
prefix: /home/servilla/miniconda3/envs/ezeml
